version: '3'
services:
  serve:
    build: .
    volumes:
      - ./src:/usr/local/tomcat/webapps
    ports:
      - "8080:4000"
    environment:
      APP_NAME: 'AccountManagementServlet'
      APP_CLASS: 'com.java_web'
    command: [ "run.sh" ]